# Generated by Django 5.0.6 on 2024-06-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
